version: '3'

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    networks:
      - api-shop
    environment:
      SWAGGER_JSON: 'http://localhost:8081/swagger/swagger.json'
  api-shop:
    build: .
    ports:
      - 8081:8081
      - 8088:8088
    networks:
      - api-shop
    command: bee run -downdoc=true -gendoc=true
    volumes:
      - .:/go/src/shop-api/
    depends_on: 
      - db-shop
    environment:
      driver: postgres
      sqlconn: postgres://user:pass@db-shop:5432/db?sslmode=disable
  db-shop:
    image: postgres:12
    volumes:
      - 'db-shop:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'db'
    networks:
      api-shop:
volumes:
  db-shop:
networks:
  api-shop: